#homePage:
#    path: /
#    controller: \App\Controller\PostController
#    action: home
#insertPost:
#    path: /insertPost
#    controller: \App\Controller\PostController
#    action: insertTest
#updatePost:
#    path: /updatePost/{id}
#    controller: \App\Controller\PostController
#    action: updatePost
#deletePost:
#    path: /deletePost/{id}
#    controller: \App\Controller\PostController
#    action: deletePost
#showPost:
#    path: /getPost/{id}
#    controller: \App\Controller\PostController
#    action: getPost
#countPost:
#    path: /countPost/
#    controller: \App\Controller\PostController
#    action: countPost
#api:
#    path: /api/{crudType}
#    controller: \App\Controller\ApiController
#    action: api
#login:
#    path: /login
#    controller: \App\Controller\UserController
#    action: login
#register:
#    path: /register
#    controller: \App\Controller\UserController
#    action: register