#homePage:
#    path: /
#    controller: \App\Controller\PostController
#    action: home
#
#showOne:
#    path: /show/{id}-{truc}
#    controller: \App\Controller\PostController
#    action: show
#
#showTest:
#    path: /show
#    controller: \App\Controller\PostController
#    action: showTest
#insertTest:
#    path: /insertTest
#    controller: \App\Controller\PostController
#    action: insertTest
#api:
#    path: /api/{crudType}
#    controller: \App\Controller\ApiController
#    action: api